### PR TITLE
Added my favourite tiger poem!

### PR DESCRIPTION
**Pull request by TidalLilac**
Addresses the issue of people not seeing art from 6-year-olds

### CODE REVIEW

**Comment by jusakihe** [comment]
🐅

**Review by PSAT-mind — APPROVED** [review]
Good kitty! :)

**Review by MahaSroor — COMMENTED** [review]
Nice poem

**Comment by PSAT-mind** [comment]
> Addresses the issue of people not seeing art from 6-year-olds

My master's thesis will address this issue

**Comment by TidalLilac** [comment]
> > Addresses the issue of people not seeing art from 6-year-olds
> 
> My master's thesis will address this issue
@PSAT-mind

Yes
YES
The issue is out

**Pull request merged**
